Manifestv2
YunoHost-Apps/digiscreen_ynh pull request #3
Opened 2023-10-02 21:58 UTC by Salamandar

2023-10-02 21:58 UTC, Salamandar commented
!testme

2023-10-03 12:03 UTC, Salamandar commented
!testme

2023-10-03 12:45 UTC, Salamandar commented
!testme

2023-10-03 13:09 UTC, Salamandar commented
!bookwormtestme

2023-10-03 16:08 UTC, ericgaspar requested changes

2023-10-03 16:08 UTC, ericgaspar commented on manifest.toml
> +description.en = "An interactive wallpaper for the classroom, face-to-face or distant"
```suggestion
description.en = "Interactive wallpaper for the classroom, face-to-face or distant"
```

2023-10-03 16:08 UTC, ericgaspar commented on manifest.toml
> +description.fr = "Un fond d'écran interactif pour la salle de classe en présence ou à distance."
```suggestion
description.fr = "Fond d'écran interactif pour la salle de classe en présence ou à distance"
```

2023-10-03 16:08 UTC, ericgaspar commented on manifest.toml
> +yunohost = ">= 11.0.10"
```suggestion
yunohost = ">= 11.2"
```

2023-10-03 16:08 UTC, ericgaspar commented on manifest.toml
> +    help.en = "Optional: a Google API key will let you insert videos from Youtube on your Digiscreen"
```suggestion
    help.en = "Optional: a Google API key will let you insert videos from YouTube on your Digiscreen"
```

2023-10-03 16:08 UTC, ericgaspar commented on manifest.toml
> +    help.fr = "Optionnel : une clé d’API Google vous permettra d’afficher des vidéos de Youtube sur votre Digiscreen."
```suggestion
    help.fr = "Optionnel : une clé d’API Google vous permettra d’afficher des vidéos de YouTube sur votre Digiscreen."
```

2023-10-03 16:08 UTC, ericgaspar commented on manifest.toml
> +    help.en = "If public, any visitor can use this app and thus will benefit from your API keys for Pixabay and Youtube."
```suggestion
    help.en = "If public, any visitor can use this app and thus will benefit from your API keys for Pixabay and YouTube."
```

2023-10-03 16:08 UTC, ericgaspar commented on manifest.toml
> +    help.fr = "Si l’application est publique, n’importe quel visiteur pourra utiliser cette application et bénéficiera donc de vos clés d’API pour Pixabay et Youtube."
```suggestion
    help.fr = "Si l’application est publique, n’importe quel visiteur pourra utiliser cette application et bénéficiera donc de vos clés d’API pour Pixabay et YouTube."
```

2023-10-03 16:13 UTC, ericgaspar commented on manifest.toml
> +    help.fr = "Si l’application est publique, n’importe quel visiteur pourra utiliser cette application et bénéficiera donc de vos clés d’API pour Pixabay et Youtube."
Also: `php-fpm.conf` -> `extra_php-fpm.conf` or removed like befor

2023-10-04 10:28 UTC, Salamandar commented
!testme

2023-10-15 09:55 UTC, Salamandar commented
!testme

2023-11-25 08:22 UTC, ericgaspar commented
!testme

2024-01-17 14:48 UTC, closed without merging